// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Term is the predicate function for term builders.
type Term func(*sql.Selector)
