// Code generated by entc, DO NOT EDIT.

package term

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the term type in the database.
	Label = "term"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uuid"
	// FieldWord holds the string denoting the word field in the database.
	FieldWord = "word"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the term in the database.
	Table = "terms"
)

// Columns holds all SQL columns for term fields.
var Columns = []string{
	FieldID,
	FieldWord,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
