// Code generated by entc, DO NOT EDIT.

package term

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the term type in the database.
	Label = "term"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "uuid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldWord holds the string denoting the word field in the database.
	FieldWord = "word"
	// FieldPostingListCompressed holds the string denoting the posting_list_compressed field in the database.
	FieldPostingListCompressed = "posting_list_compressed"
	// Table holds the table name of the term in the database.
	Table = "terms"
)

// Columns holds all SQL columns for term fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldWord,
	FieldPostingListCompressed,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PostingListCompressedValidator is a validator for the "posting_list_compressed" field. It is called by the builders before save.
	PostingListCompressedValidator func([]byte) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
