// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/YadaYuki/omochi/app/ent/invertindexcompressed"
	"github.com/YadaYuki/omochi/app/ent/predicate"
)

// InvertIndexCompressedDelete is the builder for deleting a InvertIndexCompressed entity.
type InvertIndexCompressedDelete struct {
	config
	hooks    []Hook
	mutation *InvertIndexCompressedMutation
}

// Where appends a list predicates to the InvertIndexCompressedDelete builder.
func (iicd *InvertIndexCompressedDelete) Where(ps ...predicate.InvertIndexCompressed) *InvertIndexCompressedDelete {
	iicd.mutation.Where(ps...)
	return iicd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iicd *InvertIndexCompressedDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iicd.hooks) == 0 {
		affected, err = iicd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InvertIndexCompressedMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iicd.mutation = mutation
			affected, err = iicd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iicd.hooks) - 1; i >= 0; i-- {
			if iicd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = iicd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iicd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (iicd *InvertIndexCompressedDelete) ExecX(ctx context.Context) int {
	n, err := iicd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iicd *InvertIndexCompressedDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: invertindexcompressed.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: invertindexcompressed.FieldID,
			},
		},
	}
	if ps := iicd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, iicd.driver, _spec)
}

// InvertIndexCompressedDeleteOne is the builder for deleting a single InvertIndexCompressed entity.
type InvertIndexCompressedDeleteOne struct {
	iicd *InvertIndexCompressedDelete
}

// Exec executes the deletion query.
func (iicdo *InvertIndexCompressedDeleteOne) Exec(ctx context.Context) error {
	n, err := iicdo.iicd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{invertindexcompressed.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (iicdo *InvertIndexCompressedDeleteOne) ExecX(ctx context.Context) {
	iicdo.iicd.ExecX(ctx)
}
