// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/YadaYuki/omochi/app/ent/schema"
	"github.com/YadaYuki/omochi/app/ent/term"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	termFields := schema.Term{}.Fields()
	_ = termFields
	// termDescAge is the schema descriptor for age field.
	termDescAge := termFields[0].Descriptor()
	// term.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	term.AgeValidator = termDescAge.Validators[0].(func(int) error)
	// termDescName is the schema descriptor for name field.
	termDescName := termFields[1].Descriptor()
	// term.DefaultName holds the default value on creation for the name field.
	term.DefaultName = termDescName.Default.(string)
}
